---
  name: CI/CD Pipeline for Go Server
  # Controls when the workflow will run
  on:
    push:
      branches:
        - development
        - main
        - master
        - "[0-9]+.[0-9]+.x"
    pull_request:
      branches:
        - development
        - main
        - master
        - "[0-9]+.[0-9]+.x"
    workflow_dispatch:
  
  # The sequence of runs in this workflow:
  jobs:
    lint:
      runs-on: ubuntu-latest
      timeout-minutes: 10
  
      steps:
        - run: lsb_release -a
        - run: uname -a
        - name: Check out Repository Code
          uses: actions/checkout@v4
        - run: ls -la
        - run: echo $(grep -oP 'go (\d+\.)?(\d+\.)?(\*|\d+)' ./go.mod | awk '{print $2}' | tr -d '[:space:]')
        - id: setup-go
          run: | 
            go_version=$(awk '/^go / {print $2}' go.mod)
            echo $go_version
            echo ::set-output name=go_version::$go_version
            echo "{go_version}={$(awk '/^go / {print $2}' go.mod)}" >> $GITHUB_OUTPUT
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            # The Go version to download (if necessary) and use.
            go-version: ${{ steps.setup-go.outputs.go_version }}
        - name: Install dependencies
          run: go get .
        - name: Build
          run: go build -v
        - name: Test with the Go CLI
          run: go test